steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [
    'build',
    '-t', 'gcr.io/$PROJECT_ID/cloud-data-cleaner:$COMMIT_SHA',
    '-t', 'gcr.io/$PROJECT_ID/cloud-data-cleaner:latest',
    '.'
  ]
  timeout: 600s

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-data-cleaner:$COMMIT_SHA']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/cloud-data-cleaner:latest']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy', 'cloud-data-cleaner',
    '--image', 'gcr.io/$PROJECT_ID/cloud-data-cleaner:$COMMIT_SHA',
    '--platform', 'managed',
    '--region', 'us-central1',
    '--allow-unauthenticated',
    '--set-env-vars', 'DB_HOST=$_DB_HOST,DB_USER=$_DB_USER,DB_PASSWORD=$_DB_PASSWORD,DB_NAME=$_DB_NAME,JWT_SECRET_KEY=$_JWT_SECRET_KEY',
    '--memory', '1Gi'
  ]

options:
  machineType: 'E2_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _DB_HOST: your-db-host
  _DB_USER: your-db-user
  _DB_PASSWORD: your-db-password
  _DB_NAME: your-db-name
  _JWT_SECRET_KEY: your-jwt-secret

images: ['gcr.io/$PROJECT_ID/cloud-data-cleaner']
timeout: 1800s
